name: Docker CI Pipeline
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Display Repository Files
        run: |
          pwd
          ls -la

      - name: Build Docker Image
        run: |
          docker build -t docker-demo-app:latest .

      - name: Validate Docker Compose
        run: |
          docker compose config
      - name: Upload Project Artifacts
        uses: actions/upload-artifact@v4
        with: 
          name: docker-demo-app-source
          path: .
          

  deploy:
    name: Deploy to EC2
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Application
        uses: appleboy/ssh-action@v1.0.3
        with: 
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/docker-demo-app

            git pull origin main

            docker compose down

            docker compose up -d --build
